### ISSUE TITLE
Markdown 练习

### ISSUE THREAD

**Issue by Lee-ke** [hoperyy/fe-knowledge#1]
# 钗头凤
### 莫、莫、莫。
***
***
***
### 竹林七贤
* 嵇康
* 阮籍
* 山涛
* 向秀
* 刘伶
* 王戎
* 阮咸
***
***
***
### 唐宋八大家
1. 韩愈
2. 柳宗元
3. 苏轼
4. 苏洵
5. 苏辙
6. 欧阳修
7. 王安石
8. 曾巩
***
***
***
>水调歌头
人有悲欢离合，月有阴晴圆缺，此事古难全，但愿人长久千里共婵娟！
***
***
***
#### 插入连接
[Baidu](http://www.baidu.com)
#### 插入图片
![Mou icon](http://mouapp.com/Mou_128.png)
***
***
***
*斜体*
**粗体**
***
***

**Comment by hoperyy** [comment]
写文章后面尽量用 markdown 方式写 @Lee-ke
