### ISSUE TITLE
html 语义化

### ISSUE THREAD

**Issue by Lee-ke** [hoperyy/fe-knowledge#2]
## 什么是HTML语义化
+ 通俗的说，语义化就是，明白每个标签的用途(在什么情况下使用此标签更合理)，便于开发者阅读和写出更优美的代码的同时，让浏览器爬虫和机器更好的解析
***
## 为什么要语义化
+ 有利于SEO，有助于爬虫抓取更多的有效信息，爬虫是依赖于标签来确定上下文和各个关键字的权重
+ 语义化的HTML在没有CSS的情况下，也能呈现较好的内容结构和代码结构
+ 方便其他设备的解析
+ 便于团队的开发和维护
***
## 常见的语义化标签
+ title:页面主体内容
+ h1-h6: 分级标题，h1与title协调，有利于搜索引擎优化
+ ul: 无序列表
+ ol: 有序列表
+ header: 页眉，通常包括网站的标志，主导航，全站连接以及搜索框
+ nav: 标记导航，仅对文档中重要的链接群使用
+ main: 页面的主要内容，一个页面只能使用一次。如果是web应用则包围其主要功能
+ article: 定义外部的内容，其中的内容独立于文档的其余部分
+ section: 定义文档中的节，比如章节，页眉，页脚或文档中的其他部分
+ aside: 定义其所处内容之外的内容，如侧边栏，文章的一组连接、广告、友情连接、相关产品列表等。
+ footer: 页脚，只有当父级是body时，才是整个页眉的页脚
+ small: 呈现小号字体效果，指定细则，输入免责声明、注释、署名、版权。
+ strong: 和em标签一样，属于强调文本，但它强调的程度要高一些
+ em: 将其中的文本表示为强调的内容，表现为斜体
+ mark: 部分文本高亮显示（黄色）
+ figure: 规定独立的流内容（图像、图表、照片、代码等等）（默认有40px的左右margin）
+ figcaption: 定义figure元素的标题
+ cite: 表示所包含文本对某个参考文献的引用，比如书籍杂志的标题
+ blockquoto: 定义块引用，块引用拥有他们自己的空间
+ q: 短的引述，（跨浏览器问题，尽量避免使用）
+ time: datetime属性遵循特定的格式，如果忽略此属性，文本内容必须是合法的日期或者时间格式
+ abbr: 简称或者缩写
+ dfn: 定义术语元素，与定义必须紧挨着，可以在描述列表dl元素中使用
+ address: 作者，相关人士或组织的联系信息（电子邮件地址、指向联系信息页的链接）
+ del: 移除的内容
+ ins: 添加的内容
+ code: 标记代码
+ progress 定义运行中的进度
+ meter: 定义已知范围或分数值内的标量测量 （IE不这次这个标签）

**Comment by hoperyy** [comment]
@Lee-ke 

有哪些语义化标签，都是什么意思呢？尽量自己写出来，如果是查的，就先记住，再自己写出来
