### ISSUE TITLE
CSS选择器

### ISSUE THREAD

**Issue by Lee-ke** [hoperyy/fe-knowledge#3]
# css选择器
### css三大特性
1. 继承
2. 优先级
3. 层叠
***
### css选择器分类
1. 标签选择器（如 body.div）
2. 类选择器 (如class="head")3. 
3. ID选择器 （如id="name"）
4. 全局选择器	 (如：*号)
5. 组合选择器 （如： .head .head_logo两个选择器用空格分开）
6. 后代选择器 （如： #head .nav ul li）
7. 群组选择器 （div,span,img{color:red}注意用逗号隔开） 
8. 伪类选择器（就是连接样式a元素的伪类，4种不同的状态：link、visiter、active、hover.）
9. 子选择器（如：元素的直接后代  #nav>li）
10. 相邻兄弟选择器 (如：h2+p)
11. 属性选择器 （如：可以根据某个属性是否存在或属性的值来寻找元素，一些属性可以有多个值，值之间用空格分隔 a[href] a[rel="stylesheet"]）
***
### css优先级
1. 在属性后面使用 !important会覆盖页面内任何位置定义的元素样式
2. 作为style属性写在元素内的样式（内联样式属性为1000）
3. id选择器 （权值为100）
4. 类选择器 （权值为10）
5. 标签选择器 （权值为1）
6. 通配符选择器
7. 浏览器自定义或者继承
总结排序：！important>行内样式》ID选择器>类选择器>标签>通配符>继承>浏览器默认属性
注意：如果是同一级别的，后写的会覆盖先写的样式

**Comment by hoperyy** [comment]
上面的“css优先级”这行没有转为标题 @Lee-ke

**Comment by hoperyy** [comment]
## CSS 优先级部分

style 写在元素内的样式 和 !important 的样式，哪个优先级更高呢？
@Lee-ke

**Comment by Lee-ke** [comment]
!important 优先级最高，其次是作为style属性，写在元素内部！
