### ISSUE TITLE
float

### ISSUE THREAD

**Issue by Lee-ke** [hoperyy/fe-knowledge#5]
## 浮动float
	第一： left	元素向左浮动。
	第二： right	元素向右浮动。
	第三： none	默认值。元素不浮动，并会显示在其在文本中出现的位置。
	第四： inherit	规定应该从父元素继承 float 属性的值。
 ***
	 浮动的框可以向左或向右移动，直到它的外边缘碰到包含框或另一个浮动框的边框为止。
	 由于浮动框不在文档的普通流中，所以文档的普通流中的块框表现得就像浮动框不存在一样。但其他盒子内的文本依然会为这个元素让出位置，环绕在周围。这样就可以做出文字环绕效果
***
## 浮动的特性：
        第一：浮动的元素排在同一排
        第二：浮动的元素，内容撑开宽度
        第三：浮动的元素支持所有的css样式
        第四：浮动的元素，脱离文档流
        第五：浮动的元素，提升层级半级（可以用来做一个文字环绕的效果）
***             
##  css中的定位机制：
        第一：正常文档流
        第二：float
        第三：position   
*** 
## 清除浮动的方法
	第一：给浮动元素的父元素设置属性  
		 overflow:hidden  
	第二：使用额外的标签  
		.clear{clear:both}   
	第三：使用伪元素 
		.clearfix:after{
		 	content:"" ;
			height:0;
		 	display:block;
		 	clear:both;
		}
		 .clearfix{
            zoom:1;
        }
    这三种方法的选择：
    第一种方法：会将超出的部分隐藏，如果我们希望清除浮动，但是又要保留超出的部分，那这个方法就不合适
    第二种方法：会增加许多不必要的标签
    第三种方法：常用

**Comment by hoperyy** [comment]
@Lee-ke 

标题写错了，应该是 float

**Comment by Lee-ke** [comment]
@hoperyy 已改
